#!/bin/sh /etc/rc.common

NAME=airplay
START=99

handle_airplay() {
	local config="$1"
	local bname
	local initbuf
	local port
	
	config_get bname "$1" bname "AirPort"
	config_get initbuf "$1" initbuf "220"
	config_get port "$1" port "5002"
	
	shairport -a "$bname" -b $initbuf -p $port -B "amixer set PCM 100%" -l /dev/null -d
	
}

start() {
	config_load airplay
	config_foreach handle_airplay airplay
}

stop() {
	killall shairport
}


